# Generated by Django 5.1.6 on 2025-03-20 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('website', models.URLField(null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'name'], name='showings_lo_city_c6984b_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'address'), name='unique_location')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('grand_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('prime_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('taj_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('grand_title', models.CharField(max_length=100, null=True)),
                ('prime_title', models.CharField(max_length=100, null=True)),
                ('taj_title', models.CharField(max_length=100, null=True)),
                ('normalized_title', models.CharField(db_index=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['normalized_title'],
                'indexes': [models.Index(fields=['normalized_title'], name='showings_mo_normali_684ebe_idx'), models.Index(fields=['grand_id'], name='showings_mo_grand_i_664a95_idx'), models.Index(fields=['prime_id'], name='showings_mo_prime_i_bfe923_idx'), models.Index(fields=['taj_id'], name='showings_mo_taj_id_a94f4a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('grand_id__isnull', False), ('prime_id__isnull', False), ('taj_id__isnull', False), _connector='OR'), name='at_least_one_source_id')],
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
                ('is_showing', models.BooleanField(db_index=True, default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='showings.location')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='showings.movie')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('movies', models.ManyToManyField(related_name='batches', to='showings.movie')),
                ('showings', models.ManyToManyField(related_name='batches', to='showings.showing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['date', 'time'], name='showings_sh_date_10a546_idx'),
        ),
        migrations.AddIndex(
            model_name='showing',
            index=models.Index(fields=['is_showing'], name='showings_sh_is_show_16c18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='showing',
            constraint=models.UniqueConstraint(fields=('movie', 'location', 'date', 'time'), name='unique_showing'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'created_at'], name='showings_ba_status_57d737_idx'),
        ),
    ]
