# Generated by Django 5.1.6 on 2025-03-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
