# Generated by Django 5.1.6 on 2025-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0002_showing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='is_showing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='showing',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
